### ISSUE TITLE
Solution: Content to Code

### ISSUE THREAD

**Issue by breecousineau** [breecousineau/content-to-code#1]
Hi @wendywarren

1. main - entire page content
2. h1 - main title/ company name (most important)
3. date - date of event
4. dfn - explanation of event/ page 
5. video poster - embedded video
6. h2 - content heading 
7. em - emphasizing buying tickets
8. strong - emphasis
9. data - price
10. time - time of event
11. a href - link
12. h2 - content heading 
13. ol - names in an ordered list
14. (not sure)
15. h2 - content heading 
16. p - paragraph of text 
17. (not sure)
18. dfn - definition of game
19. h2 - content heading 
20. (not sure)
21. blockquote - stand alone quote
22. -
23. cite - source
24. h2 - content heading 
25. p - paragraph of text

**Comment by wendywarren** [comment]
Hi @breecousineau,

Good attempt at matching the content with its appropriate html element. Here are some corrections for you to review:

#3 - is using the element `<time>` but you were close

#4 & 7 - `<p>` - generic paragraph of text.

#13 - the list is `<ul>` but the list is in alphabetical order so I do see why you decided that but `<ol>` items display with a preceding marker of either a number or letter. Example: 1.,2.,3., or a., b., c., etc...

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

#14 - `<li>` - a single list item.

#16, 17 & 18 - Referring to a `<dl>` description list—a grouping of terms `<dt>` and definitions `<dd>`. 

#20 - would be the `<blockquote>`

#21 - is a `<p>` because the text in a `<blockquote>` is just text

#22 - using `<footer>` to categorize this piece of information as the least important piece of content within the `<blockquote>`.

#25 - `<address>`

Let me know if you have any questions.

Wendy
